name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento
    permissions:
      contents: write
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main
          prefix: v
  
      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'

  build:
    runs-on: ubuntu-latest

    permissions:
     contents: read
     id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #x

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soren-curriculo:${{ env.IMAGE_TAG }} -f soren-curriculo/Dockerfile soren-curriculo

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/soren-curriculo:${{ env.IMAGE_TAG }}

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: ca-curriculum-api
          imageToDeploy: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/soren-curriculo:${{ env.IMAGE_TAG }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
